languages:
  - en

src_dir: ''

inputs:
  - class: InputSdmxMl_Multiple
    path_pattern: data/*.xml
    dsd: 'VN_SDG-DSD-1.4.xml'
    import_codes: true
    drop_singleton_dimensions: false

translations:
  - class: TranslationInputSdmx
    source: 'VN_SDG-DSD-1.4.xml'

site_dir: _site

schema_file: _prose.yml

reporting_status_extra_fields: []

sdmx_output_global:
  meta_reporting_type: N
  meta_ref_area: VN
  default_values:
    REF_AREA: VN
